### ISSUE TITLE
slides for better understanding

### ISSUE THREAD

**Issue by viniciusdev-br** [KDAB/kdabtv#1]
Hello, My name is Vinicius and I was in the qml course on the 4th of September at the KDE event and I would like to have the slides to improve my understanding, sorry I don't speak English very well

**Comment by tilladam** [comment]
Hi Vinicius, unfortunately we don't provide the slides for these training sessions which we provided for free to the community. We do have a lot of material available on our YouTube channel though, including an Introductory QML Training. See here: 
https://www.youtube.com/playlist?list=PL6CJYn40gN6hdNC1IGQZfVI707dh9DPRc

**Comment by glaty1719** [comment]
hello, how about closing this issue?
