### ISSUE TITLE
qml-intro: Missing Images

### ISSUE THREAD

**Issue by aamirglb** [KDAB/kdabtv#2]
Images referred in few code examples (ex-easing-curve-alltypes etc) are missing from the qml-intro/images/ folder.
It is not possible to running qml example without these images

Request you to kindly upload all images refereed in the example into the image folder.

**Comment by dangelog** [comment]
Thanks, it's indeed a small commit mistake, 795c1e7 and 96b169f add more images. Please reopen if there are still some missing.
